spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    password: type your database password
    username: type your database username
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
  h2:
    console:
      enabled: true
